FFXIVMINION_raw = 
{
	AutoWindowAssist = 
	{
		height = 300,
		width = 210,
		x = 50,
		y = 50,
	},
	AutoWindowCrafting = 
	{
		height = 300,
		width = 210,
		x = 50,
		y = 50,
	},
	AutoWindowDuty = 
	{
		height = 300,
		width = 210,
		x = 50,
		y = 50,
	},
	AutoWindowFish = 
	{
		height = 300,
		width = 210,
		x = 50,
		y = 50,
	},
	AutoWindowGather = 
	{
		height = 300,
		width = 210,
		x = 50,
		y = 50,
	},
	AutoWindowGrind = 
	{
		height = 300,
		width = 210,
		x = 50,
		y = 50,
	},
	AutoWindowHunt = 
	{
		height = 300,
		width = 210,
		x = 50,
		y = 50,
	},
	["AutoWindowImport / Export"] = 
	{
		height = 300,
		width = 260,
		x = 50,
		y = 50,
	},
	AutoWindowPVP = 
	{
		height = 300,
		width = 210,
		x = 50,
		y = 50,
	},
	["AutoWindowParty-Grind"] = 
	{
		height = 300,
		width = 210,
		x = 50,
		y = 50,
	},
	AutoWindowQuest = 
	{
		height = 300,
		width = 210,
		x = 50,
		y = 50,
	},
	AutoWindowSettings = 
	{
		height = 300,
		width = 210,
		x = 50,
		y = 50,
	},
	AutoWindowTest = 
	{
		height = 300,
		width = 210,
		x = 50,
		y = 50,
	},
	ClickCombo = 
	{
		["Filter 1"] = 
		{
			key1 = "None",
			key2 = "None",
			key3 = "None",
			value1 = 0,
			value2 = 0,
			value3 = 0,
		},
		["Filter 2"] = 
		{
			key1 = "None",
			key2 = "None",
			key3 = "None",
			value1 = 0,
			value2 = 0,
			value3 = 0,
		},
		PermaSprint = 
		{
			key1 = "None",
			key2 = "None",
			key3 = "None",
			value1 = 0,
			value2 = 0,
			value3 = 0,
		},
		["Speed Hack"] = 
		{
			key1 = "None",
			key2 = "None",
			key3 = "None",
			value1 = 0,
			value2 = 0,
			value3 = 0,
		},
		["Start/Stop"] = 
		{
			key1 = "None",
			key2 = "None",
			key3 = "None",
			value1 = 0,
			value2 = 0,
			value3 = 0,
		},
	},
	SMDefaultProfiles = 
	{
		"Gladiator",
		"Monk",
		"Marauder",
		"Lancer",
		"Archer",
		"Conjurer",
		"Black_Mage", 
		[15] = "Culinarian",
		[19] = "Paladin",
		[20] = "Monk",
		[21] = "Warrior",
		[22] = "Dragoon",
		[23] = "Bard",
		[24] = "White_Mage",
		[25] = "Black_Mage",
		[26] = "Arcanist",
		[27] = "Summoner",
		[28] = "Scholar",
		[29] = "Rogue",
		[30] = "Ninja",
	},
	completedQuestIDs = 
	{
	},
	cpOption = "",
	cpOptions = 
	{
	},
	cpTBuffs = "",
	cpTCastIDs = "",
	currentQuestObjective = 0,
	eQuestID = "",
	eQuestJob = "None",
	eQuestLevel = 1,
	eStepNum = "",
	eStepTask = "start",
	eTaskAction = "",
	eTaskCommandString = "",
	eTaskConvoIndex = 0,
	eTaskDelay = 0,
	eTaskItemAmount = 1,
	eTaskItemID = 0,
	eTaskItemSelector = 1,
	eTaskKillCount = 0,
	eTaskKillPriorities = "",
	eTaskKillTarget = "",
	eTaskMap = "",
	eTaskMesh = "",
	eTaskNPC = "",
	eTaskQuestID = 0,
	eTaskRewardSlot = 0,
	g2dRadar = "0",
	g2dRadarFullScreen = "0",
	g3dRadar = "0",
	gAFKMove = "1",
	gAlwaysKillAggro = "0",
	gAssistMode = "None",
	gAssistPriority = "Damage",
	gAtma = "0",
	gAutoStart = "0",
	gAvoidAOE = "0",
	gBotMode = "Grind",
	gChoco = "None",
	gChocoStance = "Free Stance",
	gClaimFirst = "0",
	gClaimRange = "20",
	gClaimed = "0",
	gClickToTeleport = "0",
	gClickToTravel = "0",
	gCombatRangePercent = "75",
	gConfirmDuty = "0",
	gCraftMaxItems = 0,
	gCraftMinCP = 0,
	gCurrQuestID = "",
	gCurrQuestStep = 0,
	gDisableDrawing = "0",
	gDoFates = "0",
	gDoUnstuck = "0",
	gEnableLog = "0",
	gExportAutoGlobal = "0",
	gFFXIVMINIONPulseTime = "150",
	gFateBLTimer = "120",
	gFateTeleportPercent = "0",
	gFateWaitPercent = "0",
	gFatesOnly = "0",
	gFishNoMarker = "0",
	gFleeHP = "20",
	gFleeMP = "0",
	gFood = "None",
	gFoodHQ = "None",
	gGatherBotanistGearset = "1",
	gGatherLocations = 
	{
	},
	gGatherMapClass = "MINER",
	gGatherMapHour = "",
	gGatherMapIdle = "0",
	gGatherMapMarker = "",
	gGatherMapName = "",
	gGatherMinerGearset = "1",
	gGatherPS = "0",
	gGatherStartLocation = "",
	gGatherUnspoiled = "0",
	gGatherUseCordials = "1",
	gHuntARankAllies = 2,
	gHuntARankCommandString = "",
	gHuntARankDoCommand = "0",
	gHuntARankHP = 1,
	gHuntARankHunt = "1",
	gHuntARankMaxWait = 120,
	gHuntARankSound = "0",
	gHuntBRankHunt = "1",
	gHuntBRankHuntID = "",
	gHuntBRankSound = "",
	gHuntLocations = 
	{
	},
	gHuntMapID = "",
	gHuntMapTimer = "",
	gHuntMarkerStyle = "Marker List",
	gHuntSRankAllies = 12,
	gHuntSRankCommandString = "",
	gHuntSRankDoCommand = "0",
	gHuntSRankHP = 1,
	gHuntSRankHunt = "1",
	gHuntSRankMaxWait = 120,
	gHuntSRankSound = "0",
	gImportFileName = "",
	gImportOverwriteMarkers = "",
	gKillAggroEnemies = "0",
	gLastDutyProfile = "",
	gLastQuestProfile = "",
	gLogCNE = "0",
	gLootOption = "Any",
	gMaxFateLevel = "5",
	gMinFateLevel = "0",
	gModifierKey = "None",
	gModifierKey2 = "None",
	gMount = "None",
	gMountDist = "75",
	gMultiBotEnabled = "0",
	gMultiChannel = "Group1",
	gMultiPass = "minionpw",
	gMultiPort = "7777",
	gMultiServer = "127.0.0.1",
	gPVPAvoid = "0",
	gPVPDelayLeave = "0",
	gPVPSpeedMatchPartner = "",
	gPVPTargetFive = "Lowest Health",
	gPVPTargetFour = "Lowest Health",
	gPVPTargetOne = "Healer",
	gPVPTargetThree = "Lowest Health",
	gPVPTargetTwo = "Lowest Health",
	gPartyExtraMember = "",
	gPartyGrindUsePartyLeader = "1",
	gPartyLeaderName = "",
	gPotionHP = "50",
	gPotionMP = "0",
	gPrimaryFilter = "0",
	gPrioritizeRanged = "0",
	gQuestAutoEquip = "1",
	gQuestHelpers = "0",
	gRadar = "0",
	gRadarShowAetherytes = "0",
	gRadarShowBattleNPCs = "0",
	gRadarShowEventNPCs = "0",
	gRadarShowEventObjs = "0",
	gRadarShowNode = "0",
	gRadarShowPlayers = "0",
	gRadarSpecialTargets = "2919,2920,2921,2922,2923,2924,2925,2926,2927,2928,2929,2930,2931,2932,2933,2934,2935,2936,2937,2938,2939,2940,2941,2942,2943,2944,2945,2946,2947,2948,2949,2950,2951,2952,2953,2954,2955,2956,2957,2958,2959,2960,2961,2962,2963,2964,2965,2966,2967,2968,2969",
	gRadarX = -1,
	gRadarY = -1,
	gRandomPaths = "0",
	gRepair = "1",
	gResetDutyTimer = 60,
	gRestHP = "70",
	gRestInFates = "1",
	gRestMP = "0",
	gSMactive = "1",
	gSMlastprofile = "None",
	gSecondaryFilter = "0",
	gShortcut = "Start/Stop",
	gShortcutKey = "None",
	gSkipCutscene = "0",
	gSkipDialogue = "0",
	gSprintDist = "50",
	gStartCombat = "1",
	gTeleport = "0",
	gTestQuest = "0",
	gUseAetherytes = "0",
	gUseCurielRoot = "0",
	gUseHQMats = "0",
	gUseMooch = "1",
	gUseMount = "0",
	gUseSprint = "0",
	gUseTelecast = "1",
	qDutyCustom = "",
	qDutyTask = "Kill",
	qEncounterName = "",
	qEncounterType = "kill",
	qPreReqID = "",
	qPreReqJob = "All",
	qPreReqStep = 1,
	qProfileName = "None",
	qProfileNew = "",
	qProfileType = "Duty",
	qQuestID = "",
	qQuestJob = "None",
	qQuestLevel = 1,
	qStepNum = "",
	qStepTask = "start",
	qTaskAction = "",
	qTaskCommandString = "",
	qTaskConvoIndex = 0,
	qTaskCustom = "",
	qTaskDelay = 0,
	qTaskItemAmount = 1,
	qTaskItemID = 0,
	qTaskItemJobReq = -1,
	qTaskItemSelector = 1,
	qTaskKillCount = 0,
	qTaskKillPriorities = "",
	qTaskKillTarget = "",
	qTaskMap = "",
	qTaskMesh = "",
	qTaskNPC = "",
	qTaskQuestID = 0,
	qTaskRewardSlot = 0,
	qTurnoverID = "",
	qTurnoverSlot = 1,
	qTurnoverStep = 1,
	qmWindow = 
	{
		height = 300,
		width = 250,
		x = 200,
		y = 40,
	},
	version = 1,
}



