FFXIVMINION_raw = 
{
	AutoWindowAssist = 
	{
		height = 300,
		width = 210,
		x = 0,
		y = 529,
	},
	AutoWindowController = 
	{
		height = 401,
		width = 345,
		x = 1575,
		y = 22,
	},
	AutoWindowCrafting = 
	{
		height = 300,
		width = 210,
		x = 0,
		y = 529,
	},
	AutoWindowDuty = 
	{
		height = 301,
		width = 302,
		x = 0,
		y = 478,
	},
	AutoWindowFish = 
	{
		height = 300,
		width = 253,
		x = 0,
		y = 529,
	},
	AutoWindowGather = 
	{
		height = 373,
		width = 313,
		x = 0,
		y = 529,
	},
	AutoWindowGrind = 
	{
		height = 300,
		width = 250,
		x = 0,
		y = 529,
	},
	AutoWindowHunt = 
	{
		height = 385,
		width = 227,
		x = 50,
		y = 50,
	},
	["AutoWindowImport / Export"] = 
	{
		height = 300,
		width = 260,
		x = 621,
		y = 493,
	},
	AutoWindowPVP = 
	{
		height = 300,
		width = 293,
		x = 0,
		y = 529,
	},
	["AutoWindowParty-Grind"] = 
	{
		height = 300,
		width = 210,
		x = 0,
		y = 478,
	},
	AutoWindowQuest = 
	{
		height = 300,
		width = 210,
		x = 50,
		y = 50,
	},
	AutoWindowQuickStart = 
	{
		height = 350,
		width = 210,
		x = 50,
		y = 50,
	},
	AutoWindowSettings = 
	{
		height = 300,
		width = 253,
		x = 253,
		y = 529,
	},
	AutoWindowTest = 
	{
		height = 300,
		width = 210,
		x = 50,
		y = 50,
	},
	ClickCombo = 
	{
		["Filter 1"] = 
		{
			key1 = "None",
			key2 = "None",
			key3 = "None",
			value1 = 0,
			value2 = 0,
			value3 = 0,
		},
		["Filter 2"] = 
		{
			key1 = "None",
			key2 = "None",
			key3 = "None",
			value1 = 0,
			value2 = 0,
			value3 = 0,
		},
		PermaSprint = 
		{
			key1 = "None",
			key2 = "None",
			key3 = "None",
			value1 = 0,
			value2 = 0,
			value3 = 0,
		},
		["Speed Hack"] = 
		{
			key1 = "None",
			key2 = "None",
			key3 = "None",
			value1 = 0,
			value2 = 0,
			value3 = 0,
		},
		["Start/Stop"] = 
		{
			key1 = "None",
			key2 = "None",
			key3 = "None",
			value1 = 0,
			value2 = 0,
			value3 = 0,
		},
	},
	SMDefaultProfiles = 
	{
		"Gladiator",
		"Monk",
		"Marauder",
		"Lancer",
		"Archer",
		"Conjurer",
		"Thaumaturge", 
		[13] = "750 Items",
		[15] = "Culinarian",
		[16] = "Miner",
		[17] = "Gather",
		[19] = "Paladin",
		[20] = "Monk-Ace-PVP",
		[21] = "Warrior",
		[22] = "Dragoon",
		[23] = "Bard",
		[24] = "WHM C&H 1.7",
		[25] = "BLM_50",
		[26] = "Arcanist",
		[27] = "UltimateSummoner",
		[28] = "Scholar",
		[29] = "Rogue",
		[30] = "Ninja",
	},
	completedQuestIDs = 
	{
	},
	cpOption = "",
	cpOptions = 
	{
	},
	cpTBuffs = "",
	cpTCastIDs = "",
	currentQuestObjective = 0,
	eEncounterFailTime = "1000",
	eEncounterNum = "",
	eEncounterRadius = "30",
	eEncounterTask = "kill",
	eEncounterWaitTime = "1000",
	eQuestID = "",
	eQuestJob = "None",
	eQuestLevel = 1,
	eQuestName = "",
	eStepNum = "",
	eStepTask = "start",
	eTaskAction = "",
	eTaskCommandString = "",
	eTaskConvoIndex = 0,
	eTaskDelay = 0,
	eTaskDisableAvoid = "0",
	eTaskDisableCountCheck = "0",
	eTaskDisableFlagCheck = "0",
	eTaskDisableTargetCheck = "0",
	eTaskFailTime = 0,
	eTaskIndex = 1,
	eTaskItemAmount = 1,
	eTaskItemID = 0,
	eTaskItemSelector = 1,
	eTaskKillCount = 0,
	eTaskKillPriorities = "",
	eTaskKillTarget = "",
	eTaskMap = "",
	eTaskMesh = "",
	eTaskNPC = "",
	eTaskQuestID = 0,
	eTaskRestartStep = 0,
	eTaskRewardSlot = 0,
	eTaskRewardSlotACN = "",
	eTaskRewardSlotARC = "",
	eTaskRewardSlotBLM = "",
	eTaskRewardSlotBRD = "",
	eTaskRewardSlotCNJ = "",
	eTaskRewardSlotDRG = "",
	eTaskRewardSlotDefault = "",
	eTaskRewardSlotGLD = "",
	eTaskRewardSlotLNC = "",
	eTaskRewardSlotMNK = "",
	eTaskRewardSlotMRD = "",
	eTaskRewardSlotNIN = "",
	eTaskRewardSlotPLD = "",
	eTaskRewardSlotPUG = "",
	eTaskRewardSlotROG = "",
	eTaskRewardSlotSCH = "",
	eTaskRewardSlotSMN = "",
	eTaskRewardSlotTHM = "",
	eTaskRewardSlotWAR = "",
	eTaskRewardSlotWHM = "",
	eTaskUsePos = "0",
	eTaskUsePosX = 0,
	eTaskUsePosY = 0,
	eTaskUsePosZ = 0,
	eTaskUseRewardTable = "0",
	g2dRadar = "1",
	g2dRadarFullScreen = "1",
	g3dRadar = "1",
	gAFKMove = "1",
	gAlwaysKillAggro = "0",
	gAssistMode = "None",
	gAssistPriority = "Damage",
	gAtma = "1",
	gAutoStart = "1",
	gAvoidAOE = "1",
	gBotMode = "Crafting",
	gChoco = "None",
	gChocoStance = "Free Stance",
	gClaimFirst = "1",
	gClaimRange = "20",
	gClaimed = "1",
	gClickToTeleport = "1",
	gClickToTravel = "1",
	gCombatRangePercent = "75",
	gConfirmDuty = "0",
	gCraftMaxItems = "200",
	gCraftMinCP = "0",
	gCurrQuestID = "",
	gCurrQuestStep = 0,
	gDisableDrawing = "0",
	gDoFates = "1",
	gDoUnstuck = "0",
	gDutyMapID = 0,
	gEnableLog = "0",
	gExportAutoGlobal = "0",
	gFFXIVMINIONPulseTime = "150",
	gFateBLTimer = "120",
	gFateTeleportPercent = "0",
	gFateWaitPercent = "0",
	gFatesOnly = "1",
	gFishNoMarker = "0",
	gFleeHP = "20",
	gFleeMP = "0",
	gFood = "None",
	gFoodHQ = "None",
	gGatherBotanistGearset = "12",
	gGatherLocations = 
	{
		["Cluster B 1"] = 
		{
			class = 17,
			enabled = true,
			hour = 1,
			isIdle = false,
			lastGather = 1420301281,
			mapid = 156,
			marker = "Cluster B 1",
			mesh = "Mor Dhona",
			name = "Cluster B 1",
			teleport = 24,
		},
		["Cluster B 5"] = 
		{
			class = 17,
			enabled = true,
			hour = 5,
			isIdle = false,
			lastGather = 1414330075,
			mapid = 156,
			marker = "Cluster B 5",
			mesh = "Mor Dhona",
			name = "Cluster B 5",
			teleport = 24,
		},
		["Cluster B 9"] = 
		{
			class = 17,
			enabled = true,
			hour = 9,
			isIdle = false,
			lastGather = 1414330965,
			mapid = 156,
			marker = "Cluster B 9",
			mesh = "Mor Dhona",
			name = "Cluster B 9",
			teleport = 24,
		},
		["Cluster M 13"] = 
		{
			class = 16,
			enabled = true,
			hour = 13,
			isIdle = false,
			lastGather = 1420299975,
			mapid = 156,
			marker = "Cluster M 13",
			mesh = "Mor Dhona",
			name = "Cluster M 13",
			teleport = 24,
		},
		["Cluster M 17"] = 
		{
			class = 16,
			enabled = true,
			hour = 17,
			isIdle = false,
			lastGather = 1420300584,
			mapid = 156,
			marker = "Cluster M 17",
			mesh = "Mor Dhona",
			name = "Cluster M 17",
			teleport = 24,
		},
		["Cluster M 21"] = 
		{
			class = 16,
			enabled = true,
			hour = 21,
			isIdle = false,
			lastGather = 1420300935,
			mapid = 156,
			marker = "Cluster M 21",
			mesh = "Mor Dhona",
			name = "Cluster M 21",
			teleport = 24,
		},
		Dunkelstahlerz = 
		{
			class = 16,
			enabled = true,
			hour = 1,
			isIdle = false,
			lastGather = 1414329290,
			mapid = 155,
			marker = "Dunkelstahlerz",
			mesh = "Coerthas",
			name = "Dunkelstahlerz",
			teleport = 23,
		},
		["Dzemael Tomate"] = 
		{
			class = 17,
			enabled = true,
			hour = 13,
			isIdle = false,
			lastGather = 1420299869,
			mapid = 137,
			marker = "Dzemael Tomate",
			mesh = "Eastern La Noscea - Wineport",
			name = "Dzemael Tomate",
			teleport = 12,
		},
		["Gold Ore"] = 
		{
			class = 16,
			enabled = true,
			hour = 9,
			isIdle = false,
			lastGather = 1414330760,
			mapid = 145,
			marker = "Gold Ore",
			mesh = "Eastern Thanalan",
			name = "Gold Ore",
			teleport = 18,
		},
		Kokon = 
		{
			class = 17,
			enabled = true,
			hour = 1,
			isIdle = false,
			lastGather = 1414332104,
			mapid = 152,
			marker = "Kokon",
			mesh = "East Shroud",
			name = "Kokon",
			teleport = 4,
		},
		Schattenfels = 
		{
			class = 16,
			enabled = true,
			hour = 6,
			isIdle = false,
			lastGather = 1414332968,
			mapid = 153,
			marker = "Schattenfels",
			mesh = "South Shroud",
			name = "Schattenfels",
			teleport = 6,
		},
		["Spruce Log"] = 
		{
			class = 17,
			enabled = true,
			hour = 9,
			isIdle = false,
			lastGather = 1414330613,
			mapid = 155,
			marker = "Spruce Log",
			mesh = "Coerthas",
			name = "Spruce Log",
			teleport = 23,
		},
		Steinsalz = 
		{
			class = 16,
			enabled = true,
			hour = 17,
			isIdle = false,
			lastGather = 1420300492,
			mapid = 137,
			marker = "Steinsalz",
			mesh = "Eastern La Noscea - Wineport",
			name = "Steinsalz",
			teleport = 12,
		},
		["Thanalan Topsoil"] = 
		{
			class = 16,
			enabled = true,
			hour = 5,
			isIdle = false,
			lastGather = 1414332793,
			mapid = 140,
			marker = "Thanalan Topsoil",
			mesh = "Western Thanalan",
			name = "Thanalan Topsoil",
			teleport = 17,
		},
		["Thavnair Mistelzweig"] = 
		{
			class = 17,
			enabled = true,
			hour = 17,
			isIdle = false,
			lastGather = 1420300323,
			mapid = 155,
			marker = "Thavnair Mistelzweig",
			mesh = "Coerthas",
			name = "Thavnair Mistelzweig",
			teleport = 23,
		},
		Truffle = 
		{
			class = 17,
			enabled = true,
			hour = 13,
			isIdle = false,
			lastGather = 1420299764,
			mapid = 145,
			marker = "Truffle",
			mesh = "Eastern Thanalan",
			name = "Truffle",
			teleport = 18,
		},
	},
	gGatherMapClass = "MINER",
	gGatherMapHour = "",
	gGatherMapIdle = "0",
	gGatherMapMarker = "",
	gGatherMapName = "",
	gGatherMinerGearset = "5",
	gGatherPS = "0",
	gGatherStartLocation = "Cluster B 1",
	gGatherUnspoiled = "0",
	gGatherUseCordials = "1",
	gHuntARankAllies = "2",
	gHuntARankCommandString = "",
	gHuntARankDoCommand = "0",
	gHuntARankHP = "1",
	gHuntARankHunt = "1",
	gHuntARankMaxWait = "120",
	gHuntARankSound = "1",
	gHuntBRankHunt = "1",
	gHuntBRankHuntID = "",
	gHuntBRankSound = "1",
	gHuntLocations = 
	{
		["1"] = 
		{
			mapid = "154",
			randomize = "Marker List",
			timer = 20,
		},
		["2"] = 
		{
			mapid = "148",
			randomize = "Marker List",
			timer = 20,
		},
	},
	gHuntMapID = "148",
	gHuntMapTimer = "20",
	gHuntMarkerStyle = "Marker List",
	gHuntSRankAllies = "12",
	gHuntSRankCommandString = "",
	gHuntSRankDoCommand = "0",
	gHuntSRankHP = "1",
	gHuntSRankHunt = "1",
	gHuntSRankMaxWait = "120",
	gHuntSRankSound = "1",
	gImportFileName = "",
	gImportOverwriteMarkers = "",
	gKillAggroEnemies = "0",
	gLastCompletedSteps = 
	{
	},
	gLastDutyProfile = "1) 50_StoneVigil_HM_A-2-",
	gLastQuestProfile = "",
	gLogCNE = "0",
	gLootOption = "Any",
	gMaxFateLevel = "5",
	gMinFateLevel = "50",
	gModifierKey = "None",
	gModifierKey2 = "None",
	gMount = "company chocobo",
	gMountDist = "75",
	gMultiBotEnabled = "1",
	gMultiChannel = "hh",
	gMultiPass = "zoom",
	gMultiPort = "7777",
	gMultiServer = "127.0.0.1",
	gNoMeshLoad = "0",
	gPVPAvoid = "1",
	gPVPDelayLeave = "1",
	gPVPSpeedMatchPartner = "",
	gPVPTargetFive = "Lowest Health",
	gPVPTargetFour = "Lowest Health",
	gPVPTargetOne = "Sleeper",
	gPVPTargetThree = "Lowest Health",
	gPVPTargetTwo = "Healer",
	gPVPWinTrade = "0",
	gParanoid = "1",
	gPartyExtraMember = "",
	gPartyGrindUsePartyLeader = "1",
	gPartyLeaderName = "Gangi Mangi",
	gPerformanceLevel = "Normal",
	gPermaSwiftCast = "0",
	gPotionHP = "50",
	gPotionMP = "0",
	gPrimaryFilter = "0",
	gPrioritizeRanged = "1",
	gQSGatherContent = "",
	gQSGatherItem1 = "",
	gQSGatherItem2 = "",
	gQSGatherNodeLevel = "5",
	gQSGrindContent = "",
	gQSGrindMaxLevel = "50",
	gQSGrindMinLevel = "1",
	gQuestAutoEquip = "0",
	gQuestHelpers = "0",
	gRadar = "1",
	gRadarShowAetherytes = "0",
	gRadarShowBattleNPCs = "0",
	gRadarShowEventNPCs = "0",
	gRadarShowEventObjs = "0",
	gRadarShowNode = "0",
	gRadarShowPlayers = "0",
	gRadarSpecialTargets = "2919,2920,2921,2922,2923,2924,2925,2926,2927,2928,2929,2930,2931,2932,2933,2934,2935,2936,2937,2938,2939,2940,2941,2942,2943,2944,2945,2946,2947,2948,2949,2950,2951,2952,2953,2954,2955,2956,2957,2958,2959,2960,2961,2962,2963,2964,2965,2966,2967,2968,2969",
	gRadarX = -1,
	gRadarY = -1,
	gRandomPaths = "0",
	gRepair = "1",
	gResetDutyTimer = "90",
	gRestHP = "70",
	gRestInFates = "1",
	gRestMP = "0",
	gSMactive = "1",
	gSMlastprofile = "750 Items",
	gSecondaryFilter = "0",
	gShortcut = "Start/Stop",
	gShortcutKey = "None",
	gSkipCutscene = "1",
	gSkipDialogue = "0",
	gSprintDist = "50",
	gStartCombat = "1",
	gStatusPVPLeader = "",
	gTeleport = "1",
	gTestQuest = "0",
	gUseAetherytes = "1",
	gUseCurielRoot = "0",
	gUseHQMats = "1",
	gUseMooch = "1",
	gUseMount = "1",
	gUseSprint = "1",
	gUseTelecast = "0",
	qDutyCustom = "",
	qDutyTask = "Kill",
	qEncounterName = "",
	qEncounterType = "kill",
	qPreReqID = "",
	qPreReqJob = "All",
	qPreReqStep = 1,
	qProfileName = "None",
	qProfileNew = "",
	qProfileType = "Duty",
	qQuestID = "",
	qQuestJob = "None",
	qQuestLevel = 1,
	qQuestName = "",
	qStepNum = "",
	qStepTask = "start",
	qTaskAction = "",
	qTaskCommandString = "",
	qTaskConvoIndex = 0,
	qTaskCustom = "",
	qTaskDelay = 0,
	qTaskDisableAvoid = "0",
	qTaskDisableCountCheck = "0",
	qTaskDisableFlagCheck = "0",
	qTaskDisableTargetCheck = "0",
	qTaskFailTime = 0,
	qTaskIndex = 1,
	qTaskItemAmount = 1,
	qTaskItemID = 0,
	qTaskItemJobReq = -1,
	qTaskItemSelector = 1,
	qTaskKillCount = 0,
	qTaskKillPriorities = "",
	qTaskKillTarget = "",
	qTaskMap = "",
	qTaskMesh = "",
	qTaskNPC = "",
	qTaskQuestID = 0,
	qTaskRestartStep = 0,
	qTaskRewardSlot = 0,
	qTaskRewardSlotACN = "",
	qTaskRewardSlotARC = "",
	qTaskRewardSlotBLM = "",
	qTaskRewardSlotBRD = "",
	qTaskRewardSlotCNJ = "",
	qTaskRewardSlotDRG = "",
	qTaskRewardSlotDefault = "",
	qTaskRewardSlotGLD = "",
	qTaskRewardSlotLNC = "",
	qTaskRewardSlotMNK = "",
	qTaskRewardSlotMRD = "",
	qTaskRewardSlotNIN = "",
	qTaskRewardSlotPLD = "",
	qTaskRewardSlotPUG = "",
	qTaskRewardSlotROG = "",
	qTaskRewardSlotSCH = "",
	qTaskRewardSlotSMN = "",
	qTaskRewardSlotTHM = "",
	qTaskRewardSlotWAR = "",
	qTaskRewardSlotWHM = "",
	qTaskUsePos = "0",
	qTaskUsePosX = 0,
	qTaskUsePosY = 0,
	qTaskUsePosZ = 0,
	qTaskUseRewardTable = "0",
	qTurnoverID = "",
	qTurnoverSlot = 1,
	qTurnoverStep = 1,
	qmWindow = 
	{
		height = 300,
		width = 250,
		x = 200,
		y = 0,
	},
	version = 1,
}



