minionlib_raw = 
{
	DefaultMaps = 
	{
		[128] = "Limsa (Upper)",
		[129] = "Limsa (Lower)",
		[130] = "Ul dah - Steps of Nald",
		[131] = "Ul dah - Steps of Thal",
		[132] = "New Gridania",
		[133] = "Old Gridania",
		[134] = "Middle La Noscea",
		[135] = "Lower La Noscea",
		[137] = "Eastern La Noscea - Costa Del Sol",
		[138] = "Western La Noscea",
		[139] = "Upper La Noscea - Right",
		[140] = "Western Thanalan",
		[141] = "Central Thanalan",
		[145] = "Eastern Thanalan",
		[146] = "Southern Thanalan",
		[147] = "Northern Thanalan",
		[148] = "Central Shroud",
		[152] = "East Shroud",
		[153] = "South Shroud",
		[154] = "Mining Shroud Ach 11 - 20",
		[155] = "Coerthas",
		[156] = "Mining LN Ach 11 - 20",
		[175] = "Wolves Den",
		[177] = "Gridania - Inn",
		[178] = "Ul dah - Inn",
		[179] = "Limsa Lominsa - Inn",
		[180] = "Outer La Noscea",
		[203] = "Ul dah - Heart of the Sworn",
		[204] = "Limsa Lominsa - Command",
		[205] = "Lotus Stand",
		[212] = "Waking Sands",
		[336] = "Wolves Den",
		[337] = "Wolves Den",
		[339] = "Frontline2",
		[352] = "Wolves Den",
		[376] = "Frontlines",
		[422] = "Frontlines",
	},
	gMarkerMgrMode = "Marker List",
	gNoMeshLoad = "0",
	lastSelectedMarker = 
	{
		["Botany Marker"] = "Botany 20",
		["Fishing Marker"] = "Fishing - Hidden Falls",
		["Grind Marker"] = "Fogcaller",
		["Hunt Marker"] = "Hunt1",
		["Mining Marker"] = "Summerford",
		["PVP Marker"] = "Flame Outpost",
		["Unspoiled Marker"] = "Cluster M 21",
	},
	lastSelectedMarkerType = "Grind Marker",
}



